### ISSUE TITLE
__$$GLOBAL_REWIRE_REGISTRY__ is not defined

### ISSUE THREAD

**Issue by igor-giussani** [naviapps/nw-react-boilerplate#3]
Hi Haruki,
I still a have issue with the last commit, I got this error on webkit console

Uncaught ReferenceError: __$$GLOBAL_REWIRE_REGISTRY__ is not defined
    at _getRewireRegistry__ (bundle.js:45775)
    at _getRewiredData__ (bundle.js:45781)
    at _get__ (bundle.js:45825)
    at Object.../node_modules/redbox-react/lib/index.js (bundle.js:45665)
    at __webpack_require__ (bundle.js:660)
    at fn (bundle.js:86)
    at Object.../node_modules/react-hot-loader/lib/AppContainer.dev.js (bundle.js:36786)
    at __webpack_require__ (bundle.js:660)
    at fn (bundle.js:86)
    at Object.../node_modules/react-hot-loader/lib/AppContainer.js (bundle.js:36879)
bundle.js:59611 

Node version: 8.0.0
Npm version: 5.0.0

**Comment by naviapis** [comment]
fixed it.
https://github.com/naviapps/nw-react-boilerplate/commit/b859f4e7f9e0b1de575ff38d4c5323b1c2a59d46 or master

i could not reproduce it.
Node version: v8.0.0
npm version: 5.0.1

please check.
thanks.

**Comment by igor-giussani** [comment]
Hi,
still having this issue. I've tried on 3 differente mac (2 with Sierra,  1 with El Capitain).

I've tried also on Windows 10, but the issue is different, the start script fails:

nw-react-boilerplate@0.0.6 start C:\Users\Massimo\Desktop\nw-react-boilerplate-master
> webpack-dev-server --env=dev --progress --profile --colors

10% building modules 1/1 modules 0 active{ Error: spawn run ENOENT
    at exports._errnoException (util.js:1014:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:189:19)
    at onErrorNT (internal/child_process.js:366:16)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)
    at Function.Module.runMain (module.js:607:11)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn run',
  path: 'run',
  spawnargs: [ '.' ] }
npm ERR! code ELIFECYCLE
npm ERR! errno 4294963238
npm ERR! nw-react-boilerplate@0.0.6 start: `webpack-dev-server --env=dev --progress --profile --colors`
npm ERR! Exit status 4294963238
npm ERR!
npm ERR! Failed at the nw-react-boilerplate@0.0.6 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

Are you working on Linux?
Thanks!
Igor

**Comment by naviapis** [comment]
it worked on macOS.
since i install windows 10, please wait for a while.

**Comment by naviapis** [comment]
fixed it.
https://github.com/naviapps/nw-react-boilerplate/commit/426eb46b39b90d193005cde2ee355a6bdd6f1a87 `webpack.dev.js` or master

please check.
thanks.

**Comment by naviapis** [comment]
$$GLOBAL_REWIRE_REGISTRY error

**Comment by igor-giussani** [comment]
Checked, same issue.
I tried also with yarn. :/

**Comment by igor-giussani** [comment]
I figured out how to fix it, but it's an hack of module redbox-react (node_modules/lib/index.js)

You should modify line 372:

**return __$$GLOBAL_REWIRE_REGISTRY__;**

with:

**return theGlobalVariable.__$$GLOBAL_REWIRE_REGISTRY__;**

**Comment by naviapis** [comment]
fixed it.
https://github.com/naviapps/nw-react-boilerplate/commit/1cb1c0ebed82744ad54473345fac8c4c4729e532 or `master`

it was caused by `redbox-react@1.4.2` depending on `react-hot-loader@3.0.0-beta.7`.
i added a line of `redbox-react@1.3.6` to `package.json`.

please check.
thanks.

**Comment by gius80** [comment]
Great it works!
Thanks a lot!
